### ISSUE TITLE
IAPWS for TH_multifrac example and HM for oedometer

### ISSUE THREAD

**Issue by ajacquey** [ajacquey/golem-examples#1]
- [x] The simulation TH_multifrac does not work properly when using IAPWS-based density and viscosity. This is probably just a question of time stepping.
- [x] The oedometer example is only mechanics. HM coupled version as presented in the paper is missing.

**Comment by mcacace** [comment]
Solved the issue with issue 1 on TH_multifrac. Some missing coupling terms and I would not use the IAPWS on induced frac and on the wells. Updated files attached
[TH_multi_frac.zip](https://github.com/ajacquey/golem-examples/files/5623023/TH_multi_frac.zip)

**Comment by mcacace** [comment]
Do not know how to close only the first issue ... the HM oedometer, I cannot remember how I did ... sorry!

**Comment by ajacquey** [comment]
> Solved the issue with issue 1 on TH_multifrac. Some missing coupling terms and I would not use the IAPWS on induced frac and on the wells. Updated files attached
> [TH_multi_frac.zip](https://github.com/ajacquey/golem-examples/files/5623023/TH_multi_frac.zip)

Thanks, I will have a look and push these changes.
No need to close the issue right now, I will do that when we resolved the oedometer case as well.

**Comment by ajacquey** [comment]
Issue fixed
